name: Laravel Stan

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  stan:
    name: LaravelStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute tests via phpstan
        run: vendor/bin/phpstan analyse
